
require "nokogiri"
require "open-uri"
require "pry"
require_relative "../lib/product_reviews/version"
require_relative "../lib/product_reviews/scraper"
require_relative "../lib/product_reviews/catagories"
require_relative "../lib/product_reviews/input_handler"
require_relative "../lib/product_reviews/product_controller"
require_relative "../lib/product_reviews/board"
